env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/react-in-jsx-scope: off,
  no-unused-vars: warn,
  import/no-extraneous-dependencies: warn,
  react/prop-types: off,
  react/jsx-no-useless-fragment: off

}
